version: "3.0"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-tool-api
    volumes:
      - ./:/app
    working_dir: /app
    command:
      go run /app/cmd/main.go
    ports:
      - "8081:8081"
